### ISSUE TITLE
filter: allow removals by exact string match, not only index match

### ISSUE THREAD

**Issue by Laogeodritt** [Worldbuilding/KazTron#14]
* Challenges: intuitive command syntax?
* On one hand, `.filter rem <index or page>` excludes numerical match (possible scenario: bot spam consistently uses a very identifiable string; could be dangerous because if allowed on `add`, a `rem` could accidentally hit another rule instead of the numerical match)
* Other syntaxes like `.filter rem index=x` would disallow an `index=x` string, which is unlikely enough that this might be OK. However, it's unintuitive
* Separate syntax like `.filter rem` vs. `.filter rnum` - unambiguous, but pollutes namespace, more commands to remember - slightly less user friendly?

**Comment by Laogeodritt** [comment]
@Grine-sudoscience @cxcfme Any comments appreciated. While this is an enhancement, sufficiently simple solutions *may* be streamlined into 1.3 rather than delayed to 1.4.

**Comment by cxcfme** [comment]
Of the proposed ones, `.filter rnum` seems the best compromise to me, it's a minor pollution and I feel generally our filters are single words which makes removal by string intuitive.

**Comment by Laogeodritt** [comment]
Implemented as `rem` for match, `rnum` for index
